spring.application.name=personal-finance-app

# הגדרות שרת ה-Database
spring.datasource.url=jdbc:sqlserver://media.ruppin.ac.il;databaseName=igroup109_prod;encrypt=true;trustServerCertificate=true
spring.datasource.username=igroup109
spring.datasource.password=Your_Password_Here
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# הגדרות JPA / Hibernate
# update אומר ש-Spring ייצור/יעדכן את הטבלאות עבורך אם הן לא קיימות
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# תמיכה בעברית ובקידוד
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Setting Alpha Vantage
app.alphavantage.apikey=apikey_AlphaV




